name: 'dbt_highway_psql'
version: '1.0.0'

profile: 'dbt_highway_psql'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"


models:
  dbt_highway_psql:
    staging:
      +materialized: view
    marts:
      +materialized: incremental

