dbt_highway_psql:
  outputs:
    dev:
      dbname: "highway_traffic"
      host: postgres
      pass: spark_password
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: spark_user
  target: dev